name: 'Tag Release'

on:
  push:
    branches:
      - main
      - 'release-*'
    paths:
      - version.go

jobs:
  tag-release:
    runs-on: ubuntu-24.04

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - run: /usr/bin/git config --global user.email actions@github.com
      - run: /usr/bin/git config --global user.name 'GitHub Actions Release Tagger'
      - run: hack/tag-release.sh
      - id: version
        run: echo "version=$(hack/get-version.sh)" >> "${GITHUB_OUTPUT}"
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/arm64,linux/amd64
          tags: norseto/taint-remover:v${{ steps.version.outputs.version }}
          build-args: |
            GITVERSION=${{ github.sha }}
          provenance: true
          sbom: true
      - uses: sigstore/cosign-installer@v3
      - env:
          COSIGN_YES: "true"
          IMAGE_REF: norseto/taint-remover:v${{ steps.version.outputs.version }}
          IMAGE_DIGEST: ${{ steps.build.outputs.digest }}
        run: cosign sign "${IMAGE_REF}@${IMAGE_DIGEST}"
